name: Publish to NPM

on:
  push:
    tags:
      - "v*"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    name: Build and publish package

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
          scope: '@dylmye'
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Build Package
        run: yarn build

      - name: Publish to NPM
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create_release:
    runs-on: ubuntu-latest
    name: Create GitHub release
    needs: build_and_publish

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
